### ISSUE TITLE
GUI elements if jupyer notebook on remote server?

### ISSUE THREAD

**Issue by VolkerH** [sommerc/bif_care#1]
Hi Christoph,

I put a watch on this as I also made some attempts to guide users through a worklfow using GUI elements in a notebook:
https://github.com/VolkerH/Cellprofiler_HPC_DaskJobqueue/blob/master/Run_Cellprofiler_with_Dask_jobqueue.ipynb
This is quite crude though, in particular the file selection dialog.

However, in my case the jupyter notebook runs on a remote server and not locally. I guess your GUI elements will only work if the machine displaying the notebook is the sa
me machine that runs the notebook ?

Also, leaving the remote/local issue aside: are you aware of any way to package the dependenies of a notebook (i.e. the python environment etc) such that users can be provided with an executable that starts jupyter. Although conda is fairly straightforward to developers I find myself having to set up conda and conda environments on a lot of users' machines because they are unable to do it themselves.

**Comment by sommerc** [comment]
Hi Volker,

my file selection dialogs are using Qt in the background, since I haven't found a better solution to it. Actually, I like the FileBrowser solution you found. 

The Qt probably wouldn't work when doing it on a remote machine, but haven't tested it. You are using tunneling/proxy or Jupyterhub?

> are you aware of any way to package the dependenies of a notebook
Not of sth. other then writing your own install script (e.g. .bat on Win) 

C

**Comment by VolkerH** [comment]
Hi Christoph, 

thanks for your reply. Unfortunately that seems to confirm what I thought.
Connection to Jupyter is via ssh tunnel into a SLURM Cluster node. So 
PyQt widgets would be executed on the remote process which is headless. 

The FileBrowser I found looked fine  until I started working with it a bit and found
a number of issues that make it difficult to use in practice. E.g. if you cd into a folder with many
files a lot of boxes are created and it can take quite a while for the web page layout to adjust (pushing cells down). That (in addition to the remote connection) creates so much latency that one is tempted to click again or the click events get out of sync.
Anyway thanks for your thoughts. If you happen to come across a better solution please let me know.
Will clode the issue.
